spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/ziovpo_db
    username: postgres
    password: "20040517"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: ziovpo2025
    key-store-type: PKCS12
    key-alias: server

jwt:
  secret: ThisIsAVeryLongSecretKeyAtLeast32CharsLong!!!
  access-token-expiration-ms: 900000
  refresh-token-expiration-ms: 604800000